name: Debug

on:
  push:
    branches:
      - yudong/mail

jobs:

  Mail-Tests:

    runs-on: [self-hosted, PVC_E2E]

    steps:
      - name: Test Results Overview
        run: |
          cd ${HOME}/triton-preci/pytorch/inductor_log/huggingface
          cd amp_bf16
          echo -e "============ Acc Check for HF amp_bf16 ============" | tee -a ./e2e_summary.log
          csv_lines_inf=$(cat inductor_huggingface_amp_bf16_inference_xpu_accuracy.csv | wc -l)
          echo $csv_lines_inf
          let num_total_amp_bf16=csv_lines_inf-1
          echo $num_total_amp_bf16
          #num_passed_amp_bf16_inf=$(grep "pass" inductor_huggingface_amp_bf16_inference_xpu_accuracy.csv | wc -l)
          num_passed_amp_bf16_inf=$(cat inductor_huggingface_amp_bf16_inference_xpu_accuracy.csv | grep "pass"  | wc -l)
          echo $num_passed_amp_bf16_inf
          let num_failed_amp_bf16_inf=num_total_amp_bf16-num_passed_amp_bf16_inf
          echo $num_failed_amp_bf16_inf
          amp_bf16_inf_acc_pass_rate=`awk 'BEGIN{printf "%.2f%%\n",('$num_passed_amp_bf16_inf'/'$num_total_amp_bf16')*100}'`
          echo $amp_bf16_inf_acc_pass_rate
          echo "num_total_amp_bf16: $num_total_amp_bf16" | tee -a ./e2e_summary.log
          echo "num_passed_amp_bf16_inf: $num_passed_amp_bf16_inf" | tee -a ./e2e_summary.log
          echo "num_failed_amp_bf16_inf: $num_failed_amp_bf16_inf" | tee -a ./e2e_summary.log
          echo "amp_bf16_inf_acc_pass_rate: $amp_bf16_inf_acc_pass_rate" | tee -a ./e2e_summary.log
          cd ../amp_fp16
          echo -e "============ Acc Check for HF amp_fp16 ============" | tee -a ./e2e_summary.log
          csv_lines_inf=$(cat inductor_huggingface_amp_fp16_inference_xpu_accuracy.csv | wc -l)
          echo $csv_lines_inf
          let num_total_amp_fp16=csv_lines_inf-1
          echo $num_total_amp_fp16
          num_passed_amp_fp16_inf=$(grep "pass" inductor_huggingface_amp_fp16_inference_xpu_accuracy.csv | wc -l)
          echo $num_passed_amp_fp16_inf
          let num_failed_amp_fp16_inf=num_total_amp_fp16-num_passed_amp_fp16_inf
          echo $num_failed_amp_fp16_inf
          amp_fp16_inf_acc_pass_rate=`awk 'BEGIN{printf "%.2f%%\n",('$num_passed_amp_fp16_inf'/'$num_total_amp_fp16')*100}'`
          echo $amp_fp16_inf_acc_pass_rate
          echo "num_total_amp_fp16: $num_total_amp_fp16" | tee -a ./e2e_summary.log
          echo "num_passed_amp_fp16_inf: $num_passed_amp_fp16_inf" | tee -a ./e2e_summary.log
          echo "num_failed_amp_fp16_inf: $num_failed_amp_fp16_inf" | tee -a ./e2e_summary.log
          echo "amp_fp16_inf_acc_pass_rate: $amp_fp16_inf_acc_pass_rate" | tee -a ./e2e_summary.log